export const NAMES: string = `
James;1;0;Human;;MO
John;1;0;Human;;MO
Robert;1;0;Human;;MO
Michael;1;0;Human;;MO
William;1;0;Human;;MO
David;1;0;Human;;MO
Richard;1;0;Human;;MO
Joseph;1;0;Human;;MO
Thomas;1;0;Human;;MO
Charles;1;0;Human;;MO
Christopher;1;0;Human;;MO
Daniel;1;0;Human;;MO
Matthew;1;0;Human;;MO
Anthony;1;0;Human;;MO
Donald;1;0;Human;;MO
Mark;1;0;Human;;MO
Paul;1;0;Human;;MO
Steven;1;0;Human;;MO
Andrew;1;0;Human;;MO
Kenneth;1;0;Human;;MO
Joshua;1;0;Human;;MO
George;1;0;Human;;MO
Kevin;1;0;Human;;MO
Brian;1;0;Human;;MO
Edward;1;0;Human;;MO
Ronald;1;0;Human;;MO
Timothy;1;0;Human;;MO
Jason;1;0;Human;;MO
Jeffrey;1;0;Human;;MO
Ryan;1;0;Human;;MO
Jacob;1;0;Human;;MO
Gary;1;0;Human;;MO
Nicholas;1;0;Human;;MO
Eric;1;0;Human;;MO
Stephen;1;0;Human;;MO
Jonathan;1;0;Human;;MO
Larry;1;0;Human;;MO
Justin;1;0;Human;;MO
Scott;1;0;Human;;MO
Brandon;1;0;Human;;MO
Frank;1;0;Human;;MO
Benjamin;1;0;Human;;MO
Gregory;1;0;Human;;MO
Samuel;1;0;Human;;MO
Raymond;1;0;Human;;MO
Patrick;1;0;Human;;MO
Alexander;1;0;Human;;MO
Jack;1;0;Human;;MO
Dennis;1;0;Human;;MO
Jerry;1;0;Human;;MO
Tyler;1;0;Human;;MO
Aaron;1;0;Human;;MO
Jose;1;0;Human;;MO
Henry;1;0;Human;;MO
Douglas;1;0;Human;;MO
Adam;1;0;Human;;MO
Peter;1;0;Human;;MO
Nathan;1;0;Human;;MO
Zachary;1;0;Human;;MO
Walter;1;0;Human;;MO
Kyle;1;0;Human;;MO
Harold;1;0;Human;;MO
Carl;1;0;Human;;MO
Jeremy;1;0;Human;;MO
Keith;1;0;Human;;MO
Roger;1;0;Human;;MO
Gerald;1;0;Human;;MO
Ethan;1;0;Human;;MO
Arthur;1;0;Human;;MO
Terry;1;0;Human;;MO
Christian;1;0;Human;;MO
Sean;1;0;Human;;MO
Lawrence;1;0;Human;;MO
Austin;1;0;Human;;MO
Joe;1;0;Human;;MO
Noah;1;0;Human;;MO
Jesse;1;0;Human;;MO
Albert;1;0;Human;;MO
Bryan;1;0;Human;;MO
Billy;1;0;Human;;MO
Bruce;1;0;Human;;MO
Willie;1;0;Human;;MO
Jordan;1;0;Human;;MO
Dylan;1;0;Human;;MO
Alan;1;0;Human;;MO
Ralph;1;0;Human;;MO
Gabriel;1;0;Human;;MO
Roy;1;0;Human;;MO
Juan;1;0;Human;;MO
Wayne;1;0;Human;;MO
Eugene;1;0;Human;;MO
Logan;1;0;Human;;MO
Randy;1;0;Human;;MO
Louis;1;0;Human;;MO
Russell;1;0;Human;;MO
Vincent;1;0;Human;;MO
Philip;1;0;Human;;MO
Bobby;1;0;Human;;MO
Johnny;1;0;Human;;MO
Bradley;1;0;Human;;MO


Mary;1;0;Human;;FO
Patricia;1;0;Human;;FO
Jennifer;1;0;Human;;FO
Linda;1;0;Human;;FO
Elizabeth;1;0;Human;;FO
Barbara;1;0;Human;;FO
Susan;1;0;Human;;FO
Jessica;1;0;Human;;FO
Sarah;1;0;Human;;FO
Karen;1;0;Human;;FO
Nancy;1;0;Human;;FO
Margaret;1;0;Human;;FO
Lisa;1;0;Human;;FO
Betty;1;0;Human;;FO
Dorothy;1;0;Human;;FO
Sandra;1;0;Human;;FO
Ashley;1;0;Human;;FO
Kimberly;1;0;Human;;FO
Donna;1;0;Human;;FO
Emily;1;0;Human;;FO
Michelle;1;0;Human;;FO
Carol;1;0;Human;;FO
Amanda;1;0;Human;;FO
Melissa;1;0;Human;;FO
Deborah;1;0;Human;;FO
Stephanie;1;0;Human;;FO
Rebecca;1;0;Human;;FO
Laura;1;0;Human;;FO
Sharon;1;0;Human;;FO
Cynthia;1;0;Human;;FO
Kathleen;1;0;Human;;FO
Helen;1;0;Human;;FO
Amy;1;0;Human;;FO
Shirley;1;0;Human;;FO
Angela;1;0;Human;;FO
Anna;1;0;Human;;FO
Brenda;1;0;Human;;FO
Pamela;1;0;Human;;FO
Nicole;1;0;Human;;FO
Ruth;1;0;Human;;FO
Katherine;1;0;Human;;FO
Samantha;1;0;Human;;FO
Christine;1;0;Human;;FO
Emma;1;0;Human;;FO
Catherine;1;0;Human;;FO
Debra;1;0;Human;;FO
Virginia;1;0;Human;;FO
Rachel;1;0;Human;;FO
Carolyn;1;0;Human;;FO
Janet;1;0;Human;;FO
Maria;1;0;Human;;FO
Heather;1;0;Human;;FO
Diane;1;0;Human;;FO
Julie;1;0;Human;;FO
Joyce;1;0;Human;;FO
Victoria;1;0;Human;;FO
Kelly;1;0;Human;;FO
Christina;1;0;Human;;FO
Joan;1;0;Human;;FO
Evelyn;1;0;Human;;FO
Lauren;1;0;Human;;FO
Judith;1;0;Human;;FO
Olivia;1;0;Human;;FO
Frances;1;0;Human;;FO
Martha;1;0;Human;;FO
Cheryl;1;0;Human;;FO
Megan;1;0;Human;;FO
Andrea;1;0;Human;;FO
Hannah;1;0;Human;;FO
Jacqueline;1;0;Human;;FO
Ann;1;0;Human;;FO
Jean;1;0;Human;;FO
Alice;1;0;Human;;FO
Kathryn;1;0;Human;;FO
Gloria;1;0;Human;;FO
Teresa;1;0;Human;;FO
Doris;1;0;Human;;FO
Sara;1;0;Human;;FO
Janice;1;0;Human;;FO
Julia;1;0;Human;;FO
Marie;1;0;Human;;FO
Madison;1;0;Human;;FO
Grace;1;0;Human;;FO
Judy;1;0;Human;;FO
Theresa;1;0;Human;;FO
Beverly;1;0;Human;;FO
Denise;1;0;Human;;FO
Marilyn;1;0;Human;;FO
Amber;1;0;Human;;FO
Danielle;1;0;Human;;FO
Abigail;1;0;Human;;FO
Brittany;1;0;Human;;FO
Rose;1;0;Human;;FO
Diana;1;0;Human;;FO
Natalie;1;0;Human;;FO
Sophia;1;0;Human;;FO
Alexis;1;0;Human;;FO
Lori;1;0;Human;;FO
Kayla;1;0;Human;;FO
Jane;1;0;Human;;FO

Smith;0;1;Human;;MFO
Johnson;0;1;Human;;MFO
Williams;0;1;Human;;MFO
Jones;0;1;Human;;MFO
Brown;0;1;Human;;MFO
Davis;0;1;Human;;MFO
Miller;0;1;Human;;MFO
Wilson;0;1;Human;;MFO
Moore;0;1;Human;;MFO
Taylor;0;1;Human;;MFO
Anderson;0;1;Human;;MFO
Thomas;0;1;Human;;MFO
Jackson;0;1;Human;;MFO
White;0;1;Human;;MFO
Harris;0;1;Human;;MFO
Martin;0;1;Human;;MFO
Thompson;0;1;Human;;MFO
Garcia;0;1;Human;;MFO
Martinez;0;1;Human;;MFO
Robinson;0;1;Human;;MFO
Clark;0;1;Human;;MFO
Rodriguez;0;1;Human;;MFO
Lewis;0;1;Human;;MFO
Lee;0;1;Human;;MFO
Walker;0;1;Human;;MFO
Hall;0;1;Human;;MFO
Allen;0;1;Human;;MFO
Young;0;1;Human;;MFO
Hernandez;0;1;Human;;MFO
King;0;1;Human;;MFO
Wright;0;1;Human;;MFO
Lopez;0;1;Human;;MFO
Hill;0;1;Human;;MFO
Scott;0;1;Human;;MFO
Green;0;1;Human;;MFO
Adams;0;1;Human;;MFO
Baker;0;1;Human;;MFO
Gonzalez;0;1;Human;;MFO
Nelson;0;1;Human;;MFO
Carter;0;1;Human;;MFO
Mitchell;0;1;Human;;MFO
Perez;0;1;Human;;MFO
Roberts;0;1;Human;;MFO
Turner;0;1;Human;;MFO
Phillips;0;1;Human;;MFO
Campbell;0;1;Human;;MFO
Parker;0;1;Human;;MFO
Evans;0;1;Human;;MFO
Edwards;0;1;Human;;MFO
Collins;0;1;Human;;MFO
Stewart;0;1;Human;;MFO
Sanchez;0;1;Human;;MFO
Morris;0;1;Human;;MFO
Rogers;0;1;Human;;MFO
Reed;0;1;Human;;MFO
Cook;0;1;Human;;MFO
Morgan;0;1;Human;;MFO
Bell;0;1;Human;;MFO
Murphy;0;1;Human;;MFO
Bailey;0;1;Human;;MFO
Rivera;0;1;Human;;MFO
Cooper;0;1;Human;;MFO
Richardson;0;1;Human;;MFO
Cox;0;1;Human;;MFO
Howard;0;1;Human;;MFO
Ward;0;1;Human;;MFO
Torres;0;1;Human;;MFO
Peterson;0;1;Human;;MFO
Gray;0;1;Human;;MFO
Ramirez;0;1;Human;;MFO
James;0;1;Human;;MFO
Watson;0;1;Human;;MFO
Brooks;0;1;Human;;MFO
Kelly;0;1;Human;;MFO
Sanders;0;1;Human;;MFO
Price;0;1;Human;;MFO
Bennett;0;1;Human;;MFO
Wood;0;1;Human;;MFO
Barnes;0;1;Human;;MFO
Ross;0;1;Human;;MFO
Henderson;0;1;Human;;MFO
Coleman;0;1;Human;;MFO
Jenkins;0;1;Human;;MFO
Perry;0;1;Human;;MFO
Powell;0;1;Human;;MFO
Long;0;1;Human;;MFO
Patterson;0;1;Human;;MFO
Hughes;0;1;Human;;MFO
Flores;0;1;Human;;MFO
Washington;0;1;Human;;MFO
Butler;0;1;Human;;MFO
Simmons;0;1;Human;;MFO
Foster;0;1;Human;;MFO
Gonzales;0;1;Human;;MFO
Bryant;0;1;Human;;MFO
Alexander;0;1;Human;;MFO
Russell;0;1;Human;;MFO
Griffin;0;1;Human;;MFO
Diaz;0;1;Human;;MFO
Hayes;0;1;Human;;MFO

Caladrel;1;0;Elf;;MO
Heldalel;1;0;Elf;;MO
Lanliss;1;0;Elf;;MO
Meirdrarel;1;0;Elf;;MO
Seldlon;1;0;Elf;;MO
Talathel;1;0;Elf;;MO
Variel;1;0;Elf;;MO
Zordlon;1;0;Elf;;MO
Cal;1;0;Elf;;MO
Thios;1;0;Elf;;MO
Krandres;1;0;Elf;;MO
Mielvam;1;0;Elf;;MO

Amrunelara;1;0;Elf;;FO
Dardlara;1;0;Elf;;FO
Faunra;1;0;Elf;;FO
Jathal;1;0;Elf;;FO
Merisiel;1;0;Elf;;FO
Oparal;1;0;Elf;;FO
Soumral;1;0;Elf;;FO
Tessara;1;0;Elf;;FO
Phednole;1;0;Elf;;FO
Iarnianne;1;0;Elf;;FO
Tadnehinsae;1;0;Elf;;FO
Muhhanlu;1;0;Elf;;FO
Fislillahru;1;0;Elf;;FO
Juthoss;1;0;Elf;;FO

Beivalur;0;1;Elf;;MFO
Wysaharice;0;1;Elf;;MFO
Faphyra;0;1;Elf;;MFO
Helestina;0;1;Elf;;MFO
Ellana;0;1;Elf;;MFO
Keygolor;0;1;Elf;;MFO
Trispeiros;0;1;Elf;;MFO
Ianlen;0;1;Elf;;MFO
Hercan;0;1;Elf;;MFO
Holatoris;0;1;Elf;;MFO
Shieldlinses;0;1;Elf;;MFO
Vah;0;1;Elf;;MFO
Nonremmiel;0;1;Elf;;MFO
Gollmon;0;1;Elf;;MFO
Nergullol;0;1;Elf;;MFO
Gen;0;1;Elf;;MFO
Egligar;0;1;Elf;;MFO
Sen;0;1;Elf;;MFO
Wollmunvi;0;1;Elf;;MFO
Allel;0;1;Elf;;MFO

Dolgrin;1;0;Dwarf;;MO
Grunyar;1;0;Dwarf;;MO
Harsk;1;0;Dwarf;;MO
Kazmuk;1;0;Dwarf;;MO
Morgrym;1;0;Dwarf;;MO
Rogar;1;0;Dwarf;;MO
Ack;1;0;Dwarf;;MO
Eld;1;0;Dwarf;;MO
Rarg;1;0;Dwarf;;MO
Haac;1;0;Dwarf;;MO
Dranmeg;1;0;Dwarf;;MO
Alkok;1;0;Dwarf;;MO
Wurgrig;1;0;Dwarf;;MO
Stersk;1;0;Dwarf;;MO

Agna;1;0;Dwarf;;FO
Bodill;1;0;Dwarf;;FO
Ingra;1;0;Dwarf;;FO
Kotri;1;0;Dwarf;;FO
Rusilka;1;0;Dwarf;;FO
Yangrit;1;0;Dwarf;;FO
Hull;1;0;Dwarf;;FO
Bhoth;1;0;Dwarf;;FO
Srah;1;0;Dwarf;;FO
Kirbi;1;0;Dwarf;;FO
Alwon;1;0;Dwarf;;FO
Mubni;1;0;Dwarf;;FO
Kukku;1;0;Dwarf;;FO

Brightsteam;0;1;Dwarf;;MFO
Tromwen;0;1;Dwarf;;MFO
Deepstride;0;1;Dwarf;;MFO
Jorsk;0;1;Dwarf;;MFO
Coldward;0;1;Dwarf;;MFO
Freebluff;0;1;Dwarf;;MFO
Varg;0;1;Dwarf;;MFO
Steelsteam;0;1;Dwarf;;MFO
Humblegrip;0;1;Dwarf;;MFO
Brightpelt;0;1;Dwarf;;MFO
Folwurg;0;1;Dwarf;;MFO

`;